### ISSUE TITLE
More improvements...

### ISSUE THREAD

**Issue by flashmob** [sloonz/go-maildir#2]
Hi @sloonz 

Just reporting small issues / improvements that are in my latest fork! :-)
https://github.com/flashmob/go-maildir

1. Sub folder creating improvements: It did not create subfolders if the parent folder was there, but subfolders were missing. (eg use case: administrator deletes sub-folders to delete email, but leaves Maildir there). Not necessarily a bug, just a feature for more reliability.

2. It looks like the fuzz tests were accidentally merged to master. This caused unnecessary creation since the fuzz tests were initialized in the init(). Removed the fuzz test back to a separate branch..

Would you like a PR?

**Comment by flashmob** [comment]
btw, fuzz test branch is here https://github.com/flashmob/go-maildir/tree/fuzz-tests

**Comment by sloonz** [comment]
Sorry for the delay.

> It looks like the fuzz tests were accidentally merged to master. This caused unnecessary creation since the fuzz tests were initialized in the init(). Removed the fuzz test back to a separate branch..

No, I just put 4629e76d952bb24730bbe1b4c7bc628cd54babb6 (“refactor Child func so that it would be possible to fuzz test the encoding functionality - would like to see the filename without creating it”) into master. The rest of fuzzing is on the fuzztest branch.

Could you split your changes into the subfolder changes (in another branch, or directly on master, as you prefer) and the fuzzing changes on fuzztest ?

**Comment by sloonz** [comment]
Merged, thanks
